load("@rules_zig//zig:defs.bzl", "zig_binary", "zig_test")

zig_binary(
    name = "diffusion",
    srcs = glob(["**/*.zig"]),
    main = "main.zig",
    visibility = ["//visibility:public"],
    deps = [
        "//zml",
        "@zigimg",
    ],
)

zig_test(
    name = "scheduler_test",
    main = "models/zimage/scheduler.zig",
    deps = ["//zml"],
)

zig_test(
    name = "text_encoder_test",
    main = "models/zimage/text_encoder.zig",
    deps = ["//zml"],
)
